name: docs

on:
  workflow_call:

permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
            fetch-depth: 0
      - name: Set release env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Configure the git user
        run: |
          git config user.name "versioning_user"
          git config user.email "connaisseur@securesystems.dev"
      - name: Install
        run: |
          pip install -r docs/requirements_docs.txt
      - name: Deploy
        run: |
          if [[ "${GHREF}" == "refs/tags/v"* ]];
          then
            mike deploy --push --update-aliases ${RELEASE_VERSION} latest
          elif [[ "${GHREF}" == "refs/heads/develop" ]]; then
            mike deploy --push ${RELEASE_VERSION}
          else
            mkdocs build
          fi
